"""Curated stock -> sector-index mapping for the 220-symbol universe.

Not derived from the codebase -- ``config/symbols.txt`` is a flat list with no
sector tagging, so this mapping was hand-built from standard NSE sector
classification to let backtest losses be cross-referenced against the sector
index the stock actually belongs to (e.g. was HDFCBANK.NS losing while
^NSEBANK itself was falling, or against a rising bank sector?).

Maps to one of the 11 sector indices already present in ``symbols.txt``:
^NSEBANK, NIFTY_FIN_SERVICE.NS, ^CNXIT, ^CNXAUTO, ^CNXFMCG, ^CNXMETAL,
^CNXPHARMA, ^CNXREALTY, ^CNXENERGY, ^CNXMEDIA, ^NSMIDCP.

A stock with no good sector-index fit in this set (e.g. capital goods,
defence, PSU-only categories not represented here) maps to None -- those
symbols are excluded from the sector cross-reference rather than forced into
a mismatched bucket. The broad market index (^NSEI, tracked separately via
TRADING_SCANNER_INDEX_SYMBOL) is the fallback comparison for those.
"""

SECTOR_MAP = {
    # --- Banking (^NSEBANK) ---
    "AUBANK.NS": "^NSEBANK",
    "AXISBANK.NS": "^NSEBANK",
    "BANDHANBNK.NS": "^NSEBANK",
    "BANKBARODA.NS": "^NSEBANK",
    "BANKINDIA.NS": "^NSEBANK",
    "CANBK.NS": "^NSEBANK",
    "FEDERALBNK.NS": "^NSEBANK",
    "HDFCBANK.NS": "^NSEBANK",
    "ICICIBANK.NS": "^NSEBANK",
    "IDFCFIRSTB.NS": "^NSEBANK",
    "INDIANB.NS": "^NSEBANK",
    "INDUSINDBK.NS": "^NSEBANK",
    "KOTAKBANK.NS": "^NSEBANK",
    "PNB.NS": "^NSEBANK",
    "RBLBANK.NS": "^NSEBANK",
    "SBIN.NS": "^NSEBANK",
    "UNIONBANK.NS": "^NSEBANK",
    "YESBANK.NS": "^NSEBANK",

    # --- Financial Services (broader than banks: NBFCs, insurance, AMCs, capital markets) ---
    "360ONE.NS": "NIFTY_FIN_SERVICE.NS",
    "ABCAPITAL.NS": "NIFTY_FIN_SERVICE.NS",
    "ANGELONE.NS": "NIFTY_FIN_SERVICE.NS",
    "BAJAJFINSV.NS": "NIFTY_FIN_SERVICE.NS",
    "BAJFINANCE.NS": "NIFTY_FIN_SERVICE.NS",
    "BSE.NS": "NIFTY_FIN_SERVICE.NS",
    "CAMS.NS": "NIFTY_FIN_SERVICE.NS",
    "CDSL.NS": "NIFTY_FIN_SERVICE.NS",
    "CHOLAFIN.NS": "NIFTY_FIN_SERVICE.NS",
    "HDFCAMC.NS": "NIFTY_FIN_SERVICE.NS",
    "HDFCLIFE.NS": "NIFTY_FIN_SERVICE.NS",
    "ICICIGI.NS": "NIFTY_FIN_SERVICE.NS",
    "ICICIPRULI.NS": "NIFTY_FIN_SERVICE.NS",
    "IEX.NS": "NIFTY_FIN_SERVICE.NS",
    "IREDA.NS": "NIFTY_FIN_SERVICE.NS",
    "IRFC.NS": "NIFTY_FIN_SERVICE.NS",
    "JIOFIN.NS": "NIFTY_FIN_SERVICE.NS",
    "KFINTECH.NS": "NIFTY_FIN_SERVICE.NS",
    "LICHSGFIN.NS": "NIFTY_FIN_SERVICE.NS",
    "LICI.NS": "NIFTY_FIN_SERVICE.NS",
    "LTF.NS": "NIFTY_FIN_SERVICE.NS",
    "MANAPPURAM.NS": "NIFTY_FIN_SERVICE.NS",
    "MFSL.NS": "NIFTY_FIN_SERVICE.NS",
    "MOTILALOFS.NS": "NIFTY_FIN_SERVICE.NS",
    "MUTHOOTFIN.NS": "NIFTY_FIN_SERVICE.NS",
    "PAYTM.NS": "NIFTY_FIN_SERVICE.NS",
    "PFC.NS": "NIFTY_FIN_SERVICE.NS",
    "PNBHOUSING.NS": "NIFTY_FIN_SERVICE.NS",
    "POLICYBZR.NS": "NIFTY_FIN_SERVICE.NS",
    "RECLTD.NS": "NIFTY_FIN_SERVICE.NS",
    "SBICARD.NS": "NIFTY_FIN_SERVICE.NS",
    "SBILIFE.NS": "NIFTY_FIN_SERVICE.NS",
    "SHRIRAMFIN.NS": "NIFTY_FIN_SERVICE.NS",

    # --- IT (^CNXIT) ---
    "COFORGE.NS": "^CNXIT",
    "HCLTECH.NS": "^CNXIT",
    "INFY.NS": "^CNXIT",
    "KPITTECH.NS": "^CNXIT",
    "LTM.NS": "^CNXIT",
    "MPHASIS.NS": "^CNXIT",
    "NAUKRI.NS": "^CNXIT",
    "OFSS.NS": "^CNXIT",
    "PERSISTENT.NS": "^CNXIT",
    "TATAELXSI.NS": "^CNXIT",
    "TCS.NS": "^CNXIT",
    "TECHM.NS": "^CNXIT",
    "WIPRO.NS": "^CNXIT",

    # --- Auto (^CNXAUTO) ---
    "ASHOKLEY.NS": "^CNXAUTO",
    "BAJAJ-AUTO.NS": "^CNXAUTO",
    "BHARATFORG.NS": "^CNXAUTO",
    "BOSCHLTD.NS": "^CNXAUTO",
    "EICHERMOT.NS": "^CNXAUTO",
    "FORCEMOT.NS": "^CNXAUTO",
    "HEROMOTOCO.NS": "^CNXAUTO",
    "HYUNDAI.NS": "^CNXAUTO",
    "M&M.NS": "^CNXAUTO",
    "MARUTI.NS": "^CNXAUTO",
    "MOTHERSON.NS": "^CNXAUTO",
    "SONACOMS.NS": "^CNXAUTO",
    "TATAMOTORS.NS": "^CNXAUTO",
    "TMPV.NS": "^CNXAUTO",
    "TVSMOTOR.NS": "^CNXAUTO",
    "UNOMINDA.NS": "^CNXAUTO",

    # --- FMCG (^CNXFMCG) ---
    "BRITANNIA.NS": "^CNXFMCG",
    "COLPAL.NS": "^CNXFMCG",
    "DABUR.NS": "^CNXFMCG",
    "GODFRYPHLP.NS": "^CNXFMCG",
    "GODREJCP.NS": "^CNXFMCG",
    "HINDUNILVR.NS": "^CNXFMCG",
    "ITC.NS": "^CNXFMCG",
    "MARICO.NS": "^CNXFMCG",
    "NESTLEIND.NS": "^CNXFMCG",
    "PATANJALI.NS": "^CNXFMCG",
    "RADICO.NS": "^CNXFMCG",
    "TATACONSUM.NS": "^CNXFMCG",
    "UNITDSPR.NS": "^CNXFMCG",
    "VBL.NS": "^CNXFMCG",

    # --- Metal (^CNXMETAL) ---
    "APLAPOLLO.NS": "^CNXMETAL",
    "HINDALCO.NS": "^CNXMETAL",
    "HINDZINC.NS": "^CNXMETAL",
    "JINDALSTEL.NS": "^CNXMETAL",
    "JSWSTEEL.NS": "^CNXMETAL",
    "NATIONALUM.NS": "^CNXMETAL",
    "NMDC.NS": "^CNXMETAL",
    "SAIL.NS": "^CNXMETAL",
    "TATASTEEL.NS": "^CNXMETAL",
    "VEDL.NS": "^CNXMETAL",

    # --- Pharma (^CNXPHARMA) ---
    "ALKEM.NS": "^CNXPHARMA",
    "AUROPHARMA.NS": "^CNXPHARMA",
    "BIOCON.NS": "^CNXPHARMA",
    "CIPLA.NS": "^CNXPHARMA",
    "DIVISLAB.NS": "^CNXPHARMA",
    "DRREDDY.NS": "^CNXPHARMA",
    "GLENMARK.NS": "^CNXPHARMA",
    "LAURUSLABS.NS": "^CNXPHARMA",
    "LUPIN.NS": "^CNXPHARMA",
    "MANKIND.NS": "^CNXPHARMA",
    "SUNPHARMA.NS": "^CNXPHARMA",
    "TORNTPHARM.NS": "^CNXPHARMA",
    "ZYDUSLIFE.NS": "^CNXPHARMA",

    # --- Realty (^CNXREALTY) ---
    "DLF.NS": "^CNXREALTY",
    "GODREJPROP.NS": "^CNXREALTY",
    "LODHA.NS": "^CNXREALTY",
    "OBEROIRLTY.NS": "^CNXREALTY",
    "PHOENIXLTD.NS": "^CNXREALTY",
    "PRESTIGE.NS": "^CNXREALTY",

    # --- Energy (^CNXENERGY) ---
    "ADANIENSOL.NS": "^CNXENERGY",
    "ADANIGREEN.NS": "^CNXENERGY",
    "ADANIPOWER.NS": "^CNXENERGY",
    "BPCL.NS": "^CNXENERGY",
    "COALINDIA.NS": "^CNXENERGY",
    "GAIL.NS": "^CNXENERGY",
    "HINDPETRO.NS": "^CNXENERGY",
    "IOC.NS": "^CNXENERGY",
    "JSWENERGY.NS": "^CNXENERGY",
    "NHPC.NS": "^CNXENERGY",
    "NTPC.NS": "^CNXENERGY",
    "OIL.NS": "^CNXENERGY",
    "ONGC.NS": "^CNXENERGY",
    "PETRONET.NS": "^CNXENERGY",
    "POWERGRID.NS": "^CNXENERGY",
    "POWERINDIA.NS": "^CNXENERGY",
    "PREMIERENE.NS": "^CNXENERGY",
    "RELIANCE.NS": "^CNXENERGY",
    "SOLARINDS.NS": "^CNXENERGY",
    "SUZLON.NS": "^CNXENERGY",
    "TATAPOWER.NS": "^CNXENERGY",
    "WAAREEENER.NS": "^CNXENERGY",

    # --- Media (^CNXMEDIA) ---
    "NYKAA.NS": "^CNXMEDIA",
    "SWIGGY.NS": "^CNXMEDIA",

    # --- Midcap catch-all (^NSMIDCP) for names that don't cleanly fit a
    # sector index above but are frequently classified under midcap 150 ---
    "AARTIIND.NS": "^NSMIDCP",
    "ABB.NS": "^NSMIDCP",
    "ADANIENT.NS": "^NSMIDCP",
    "ADANIPORTS.NS": "^NSMIDCP",
    "AMBER.NS": "^NSMIDCP",
    "AMBUJACEM.NS": "^NSMIDCP",
    "APOLLOHOSP.NS": "^NSMIDCP",
    "ASIANPAINT.NS": "^NSMIDCP",
    "ASTRAL.NS": "^NSMIDCP",
    "BAJAJHLDNG.NS": "^NSMIDCP",
    "BDL.NS": "^NSMIDCP",
    "BEL.NS": "^NSMIDCP",
    "BHARTIARTL.NS": "^NSMIDCP",
    "BHEL.NS": "^NSMIDCP",
    "BLUESTARCO.NS": "^NSMIDCP",
    "CGPOWER.NS": "^NSMIDCP",
    "COCHINSHIP.NS": "^NSMIDCP",
    "CONCOR.NS": "^NSMIDCP",
    "CROMPTON.NS": "^NSMIDCP",
    "CUMMINSIND.NS": "^NSMIDCP",
    "DALBHARAT.NS": "^NSMIDCP",
    "DELHIVERY.NS": "^NSMIDCP",
    "DIXON.NS": "^NSMIDCP",
    "DMART.NS": "^NSMIDCP",
    "ETERNAL.NS": "^NSMIDCP",
    "FORTIS.NS": "^NSMIDCP",
    "GMRAIRPORT.NS": "^NSMIDCP",
    "GRASIM.NS": "^NSMIDCP",
    "GVT&D.NS": "^NSMIDCP",
    "HAL.NS": "^NSMIDCP",
    "HAVELLS.NS": "^NSMIDCP",
    "IDEA.NS": "^NSMIDCP",
    "INDHOTEL.NS": "^NSMIDCP",
    "INDIGO.NS": "^NSMIDCP",
    "INDUSTOWER.NS": "^NSMIDCP",
    "INOXWIND.NS": "^NSMIDCP",
    "JUBLFOOD.NS": "^NSMIDCP",
    "LT.NS": "^NSMIDCP",
    "KALYANKJIL.NS": "^NSMIDCP",
    "KAYNES.NS": "^NSMIDCP",
    "KEI.NS": "^NSMIDCP",
    "MAXHEALTH.NS": "^NSMIDCP",
    "MAZDOCK.NS": "^NSMIDCP",
    "MCX.NS": "^NSMIDCP",
    "NAM-INDIA.NS": "^NSMIDCP",
    "NBCC.NS": "^NSMIDCP",
    "PAGEIND.NS": "^NSMIDCP",
    "PGEL.NS": "^NSMIDCP",
    "PIDILITIND.NS": "^NSMIDCP",
    "PIIND.NS": "^NSMIDCP",
    "POLYCAB.NS": "^NSMIDCP",
    "RVNL.NS": "^NSMIDCP",
    "SHREECEM.NS": "^NSMIDCP",
    "SIEMENS.NS": "^NSMIDCP",
    "SRF.NS": "^NSMIDCP",
    "SUPREMEIND.NS": "^NSMIDCP",
    "TIINDIA.NS": "^NSMIDCP",
    "TITAN.NS": "^NSMIDCP",
    "TRENT.NS": "^NSMIDCP",
    "ULTRACEMCO.NS": "^NSMIDCP",
    "UPL.NS": "^NSMIDCP",
    "VMM.NS": "^NSMIDCP",
    "VOLTAS.NS": "^NSMIDCP",
}


def sector_for(symbol: str) -> str | None:
    """Return the sector-index symbol a stock is mapped to, or None if unmapped."""
    return SECTOR_MAP.get(symbol)
